# Generated by Django 4.1.1 on 2022-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
