# Generated by Django 4.1.1 on 2022-10-10 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadmus', '0002_alter_entry_options_entry_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='time',
        ),
        migrations.AddField(
            model_name='entry',
            name='initial_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
