# Generated by Django 4.1.1 on 2022-10-14 19:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmus', '0003_alter_entry_options_remove_entry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
        migrations.AddField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name=''),
        ),
    ]
