# Generated by Django 4.1.1 on 2022-10-30 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadmus', '0004_remove_entry_description_entry_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='initial_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=''),
        ),
    ]
